language: python
python:
  - "3.6.7"      # current default Python on Travis CI
# command to install dependencies

install:
  - pip install -r requirements.txt
  
# command to run tests
script:
  - python3 -m unittest discover -s tests